'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChangeEFT

    '''<summary>
    '''frmEFT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmEFT As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOAT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAT1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAN1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtORN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORN1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAmt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAmt1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAT2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAN2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtORN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORN2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAmt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAmt2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAT3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAN3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAN3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtORN3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORN3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAmt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAmt3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAT4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAN4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtORN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORN4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAmt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAmt4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAT5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAN5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAN5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtORN5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORN5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOAmt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOAmt5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbAT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAT1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAN1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRN1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmt1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbAT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAT2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAN2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRN2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmt2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbAT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAT3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAN3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAN3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRN3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRN3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmt3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbAT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAT4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAN4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRN4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmt4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbAT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAT5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAN5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAN5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRN5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRN5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmt5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVoidCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVoidCheck As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEffDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChangeReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChangeReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tblUndo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblUndo As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtUndoNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUndoNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdEmailReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEmailReq As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPost As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtClockId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClockId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManClockId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManClockId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEFTCId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFTCId1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEFTCId2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFTCId2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEFTCId3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFTCId3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEFTCId4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFTCId4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEFTCId5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFTCId5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtEmpSig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpSig As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtId As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
