'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageEmpRequests

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblTitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStore1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbReqType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbReqType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''optDateC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDateC As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lbldc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblstartdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstartdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblenddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblenddate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmpClockId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpClockId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''optDateE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optDateE As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lbldeff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldeff As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdGetReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGetReq As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkApproved As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAppOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppOnly As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkManOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkManOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblsal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblMoveEditSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMoveEditSubmit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cmdMoveOA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMoveOA As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdEditPunch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditPunch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdSubmitPayroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmitPayroll As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtSelChanged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelChanged As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSort As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLoadForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoadForm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManClockId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManClockId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSecCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hlinkEnterReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlinkEnterReq As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlinkUpdateQuickHires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlinkUpdateQuickHires As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlinkProcessReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlinkProcessReq As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlinkReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlinkReports As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lbtnHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnHelp As Global.System.Web.UI.WebControls.LinkButton
End Class
